[main]
font=Noto Sans:size=12
fields=name,generic,comment,exec
terminal=alacritty
prompt="🔍 Cari Aplikasi:  "
icon-theme=Adwaita
width=40
tabs=4
lines=10
inner-pad=10

[colors]
# Format warna: RRGGBBAA (Merah, Hijau, Biru, Transparansi)
background=1e1e2ecc
text=cdd6f4ff
match=f38ba8ff
selection=313244ff
selection-text=cdd6f4ff
border=89b4faff

[border]
width=2
radius=10
